version: "3.8"


services:
  app:
    image: hello:latest
    build:
      context: .
    environment:
      LOG_LEVEL: "info"
      DB_HOSTNAME: ${POSTGRES_HOSTNAME}
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - '8081:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

