version: "3.8"

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL}

services:
  app:
    image: hello:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      DB_HOSTNAME: db
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data:
